spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  jmx:
    enabled: false
server:
  port: 8081
dev-platform:
  file-dir: D:\baseDir

