spring:
  redis:
    port: 6379
    host: 192.168.42.136
    password:
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  port: 8081
